development:
  adapter: postgresql
  encoding: unicode
  pool: 25
  database: blog
  username: nykdev
  password: nykdev
  host: 127.0.0.1
  template: template0

test:
  adapter: postgresql
  encoding: unicode
  pool: 25
  database: blog
  username: nykdev
  password: nykdev
  host: 127.0.0.1
  template: template0

staging:
  adapter: postgresql
  encoding: unicode
  pool: 25
  database: <%= ENV["PG_DATABASE"] %>
  username: <%= ENV["PG_USERNAME"] %>
  password: <%= ENV["PG_PASSWORD"] %>
  host: <%= ENV["PG_HOST"] %>
  template: template0

production:
  adapter: postgresql
  encoding: unicode
  pool: 25
  database: <%= ENV["PG_DATABASE"] %>
  username: <%= ENV["PG_USERNAME"] %>
  password: <%= ENV["PG_PASSWORD"] %>
  host: <%= ENV["PG_HOST"] %>
  template: template0

# SecondBase - second database
secondbase:
  development:
    adapter: mysql
    encoding: utf8
    pool: 25
    database: <%= ENV['NALC_TMS_DB_DATABASE'] %>
    username: <%= ENV['NALC_TMS_DB_USER'] %>
    password: <%= ENV['NALC_TMS_DB_PASSWORD'] %>
    host: <%= ENV['NALC_TMS_DB_HOST'] %>

  test:
    adapter: mysql
    encoding: utf8
    pool: 25
    database: <%= ENV['NALC_TMS_DB_DATABASE'] %>
    username: <%= ENV['NALC_TMS_DB_USER'] %>
    password: <%= ENV['NALC_TMS_DB_PASSWORD'] %>
    host: <%= ENV['NALC_TMS_DB_HOST'] %>

  staging:
    adapter: mysql
    encoding: utf8
    pool: 25
    database: <%= ENV['NALC_TMS_DB_DATABASE'] %>
    username: <%= ENV['NALC_TMS_DB_USER'] %>
    password: <%= ENV['NALC_TMS_DB_PASSWORD'] %>
    host: <%= ENV['NALC_TMS_DB_HOST'] %>

  production:
    adapter: mysql
    encoding: utf8
    pool: 25
    database: <%= ENV['NALC_TMS_DB_DATABASE'] %>
    username: <%= ENV['NALC_TMS_DB_USER'] %>
    password: <%= ENV['NALC_TMS_DB_PASSWORD'] %>
    host: <%= ENV['NALC_TMS_DB_HOST'] %>
